name: ivcython
dependencies:
  - python=3.6
#  - gcc_linux-64  # clang_osx-64 gcc_linux-64
#  - gxx_linux-64  # clangxx_osx-64 gxx_linux-64
#  - gfortran_linux-64  # gfortran_osx-64 gfortran_linux-64
  - openblas
  - pip:
    - cython
    - numpy
